from dotenv import load_dotenv
from hana_ml import dataframe
import os
from hana_ml.dataframe import create_dataframe_from_pandas

load_dotenv()

host = str(os.getenv("HANA_HOST"))


def get_hana_db():
    connection = dataframe.ConnectionContext(
        address=host,
        port=443,
        user=str(os.getenv("HANA_USER")),
        password=str(os.getenv("HANA_PASSWORD")),
    )
    return connection


# getting connection object
conn = get_hana_db()


create_table_sql = """
CREATE COLUMN TABLE documents_embedding (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_text NVARCHAR(5000),
    embedding REAL_VECTOR(1536),
    chunk_metadata NVARCHAR(1000)
)
"""

# Executing table creation
conn.execute_sql(create_table_sql)
print("table created successfully")


# inserting new record
import json


def batch_insertion_embedding(rows):
    conn_ctx = get_hana_db()
    """
    args:
        - rows : list of tuples -> [(document_text: str, embedding_string: str, metadata_json: str), ...]
    """
    sql = "INSERT INTO documents_embedding (document_text, embedding, chunk_metadata) VALUES (?, TO_REAL_VECTOR(?), ?)"
    try:
        cursor = conn_ctx.connection.cursor()
        cursor.executemany(sql, rows)
        conn_ctx.connection.commit()
        cursor.close()
        return True
    except Exception as e:
        print(f"failed to execute batch insert: {e}")
        return False


def insert_embedding(document_text, embedding_vector, chunk_metadata=None):
    conn = get_hana_db()

    # escaping text for SQL
    escaped_text = document_text.replace("'", "''")

    # Converting metadata dict to JSON string and escaping it
    if chunk_metadata:
        metadata_json = json.dumps(chunk_metadata)
        escaped_metadata = metadata_json.replace("'", "''")
    else:
        escaped_metadata = "{}"

    insert_sql = f"""
    INSERT INTO documents_embedding (document_text, embedding, chunk_metadata)
    VALUES ('{escaped_text}', TO_REAL_VECTOR('{str(embedding_vector)}'), '{escaped_metadata}')
    """

    try:
        conn.execute_sql(insert_sql)
        print("successfully inserted document and embedding")
        return True
    except Exception as e:
        return False


# function to find top k similiar documents
# ...existing code...
def search_similiar_documents(query_embedding, top_k=5):
    conn = get_hana_db()

    # Escape and format inputs
    vec = str(query_embedding).replace("'", "''")
    k = int(top_k) if top_k else 5
    if k <= 0:
        k = 5

    search_sql = f"""
    SELECT DOCUMENT_TEXT,
           CHUNK_METADATA,
           COSINE_SIMILARITY(EMBEDDING, TO_REAL_VECTOR('{vec}')) AS SIMILARITY
    FROM DOCUMENTS_EMBEDDING
    ORDER BY SIMILARITY DESC
    LIMIT {k}
    """
    try:
        df = conn.sql(search_sql)  # SELECT -> no params here
        results = df.collect()
        print(results)
        return results
    except Exception as e:
        print(f"error searching similar documents: {e}")
        return None

# function to get all the data from database
def get_all_data():
    conn = get_hana_db()
    sql = "SELECT * FROM documents_embedding"
    try:
        df = conn.sql(sql)
        results = df.collect()
        print(results)
        return results
    except Exception as e:
        print(f"error fetching all data: {e}")
        return None